// src/stencil-empty.tsx
import { Component, Prop, State, Listen, h } from '@stencil/core';
import { version } from './stencil-version.js';

@Component({
  tag: 'stencil-empty',
  styleUrl: 'stencil-empty.css',
  shadow: true
})
export class StencilComponent {
  @Prop() text: string;
  @State() lastPing: string = null;

  @Listen('framework-ping', { target: 'window' })
  onFrameworkPing(event: CustomEvent) {
    this.lastPing = event.detail;
  }

  ping() {
    window.dispatchEvent(new CustomEvent('framework-ping', {
      detail: 'stencil-empty', bubbles: true, composed: true
    }));
  }

  render() {
    return <span>
      {this.text}<br/>
      <button onClick={() => this.ping()}>Ping</button>
      {this.lastPing && <span> ← {this.lastPing}</span>}<br/>
      <small style={{textAlign: 'right', display: 'block'}}>Stencil {version}</small>
    </span>;
  }
}

// cli_based_builds/angular/src/app/angular-empty/angular-empty.component.ts
import { Component, Input, OnInit, OnDestroy, VERSION, signal } from '@angular/core';

@Component({
  standalone: true,
  selector: 'angular-empty',
  templateUrl: './angular-empty.component.html',
  styleUrls: ['./angular-empty.component.css']
})
export class AngularEmptyComponent implements OnInit, OnDestroy {
  @Input() text: string = '';
  version = VERSION.full;
  lastPing = signal<string | null>(null);

  private onPing = (e: Event) => {
    this.lastPing.set((e as CustomEvent).detail);
  };

  ngOnInit() {
    window.addEventListener('framework-ping', this.onPing);
  }

  ngOnDestroy() {
    window.removeEventListener('framework-ping', this.onPing);
  }

  ping() {
    window.dispatchEvent(new CustomEvent('framework-ping', {
      detail: 'angular-empty', bubbles: true, composed: true
    }));
  }
}

{{text}}<br>
<button (click)="ping()">Ping</button>
@if (lastPing()) { <span> ← {{lastPing()}}</span> }<br>
<small style="text-align: right; display: block;">Angular {{version}}</small>
